const reference = 'https://github.com/UltraCart/storefront-agent-toolchain/blob/master/skills/build-ultracart-storefronts/references/';
export const categories = ['All', 'Understand', 'Build', 'Preview & publish', 'Improve'];
export const capabilities = [
  {
    id: 'explore', category: 'Understand', icon: 'map', title: 'Find your way around',
    description: 'Explore pages and find the templates that bring them to life.',
    outcome: 'Understand how a page is built before changing it.', tags: 'site structure tree navigation shared dependencies',
    steps: ['List the pages in your storefront, including hidden pages.', 'Find the template that actually renders a selected page.', 'List other pages that use that template.'],
    needs: 'An authenticated merchant profile and a storefront ID.',
    limit: 'A template lookup is not a complete dependency map. Page templates must be resolved from store data.',
    commands: ['uc-storefront sf pages list --storefront <id>', 'uc-storefront sf template find --storefront <id> --uri <page-path>'],
    doc: 'pages.md', access: 'Read only',
  },
  {
    id: 'discover', category: 'Understand', icon: 'spark', title: 'Discover building blocks',
    description: 'Find an element by what you want it to do, then explore its options.',
    outcome: 'Find the right native storefront element for an idea.', tags: 'capabilities catalog schemas widgets components features accordion video form',
    steps: ['Search the element catalog using your intent.', 'Read purpose, interactions, and known limitations.', 'Inspect supported settings and responsive properties.'],
    needs: 'The installed toolkit and its bundled catalog. No merchant login is needed.',
    limit: 'The bundled catalog may differ from the current server. Catalog guidance does not prove behavior on a particular store.',
    commands: ['uc-storefront element search <idea>', 'uc-storefront element explain <type>', 'uc-storefront schema show <type>'],
    doc: 'cli-cjson.md', access: 'Local',
  },
  {
    id: 'locate', category: 'Understand', icon: 'target', title: 'Find an element’s source',
    description: 'Trace a widget on a page to its container and position in the source.',
    outcome: 'Know which widget and file to edit.', tags: 'selector click browser inspect widget source locate',
    steps: ['Provide the page path and a widget ID or supported selector.', 'Follow the template’s container references.', 'Read the matching widget, file, and reference chain.'],
    needs: 'A storefront ID, page path, and widget-rooted selector or widget ID.',
    limit: 'Dynamic template references, custom markup, and item container slots may not resolve. The command reports gaps.',
    commands: ['uc-storefront sf locate <widget-id> --storefront <id> --uri <page-path>'],
    doc: 'pages.md', access: 'Read only',
  },
  {
    id: 'edit', category: 'Build', icon: 'layout', title: 'Reshape a section',
    description: 'Change text, layout, and supported mobile settings with native widgets.',
    outcome: 'Produce a validated local content change, ready for preview.', tags: 'responsive mobile desktop copy design spacing CJSON add move remove',
    steps: ['Pull the current content and preserve its baseline.', 'Add, update, move, or remove widgets in the local file.', 'Validate the result and inspect a dry run before publishing.'],
    needs: 'A pulled CJSON file. New remote widgets require reserved server IDs.',
    limit: 'Validation checks structure and supported settings. It does not prove visual quality or checkout behavior.',
    commands: ['uc-storefront cjson tree <file>', 'uc-storefront cjson context <file> <selector>', 'uc-storefront cjson validate <file>'],
    doc: 'cli-cjson.md', access: 'Local edit',
  },
  {
    id: 'page', category: 'Build', icon: 'page', title: 'Create a landing page',
    description: 'Create or duplicate a page, choose its templates, and set its visibility.',
    outcome: 'A new page with deliberate template and indexing settings.', tags: 'landing campaign ads duplicate copy hidden noindex SEO',
    steps: ['Inspect a working page and the available templates.', 'Create a page or duplicate an eligible existing page.', 'Set its content, visibility, and search indexing explicitly.'],
    needs: 'An existing parent page, valid templates, and write/publish permissions.',
    limit: 'Page creation changes live store data. Moving, renaming, and deleting pages remain in the store admin. Noindex does not cascade to children.',
    commands: ['uc-storefront sf pages templates --storefront <id> --type group', 'uc-storefront sf pages create --help', 'uc-storefront sf pages duplicate --help'],
    doc: 'pages.md', access: 'Live write',
  },
  {
    id: 'recipe', category: 'Build', icon: 'blocks', title: 'Reuse a good section',
    description: 'Capture a widget subtree as a recipe and find it again for future work.',
    outcome: 'A reusable starting point for another section.', tags: 'recipes library reuse reusable save component pattern',
    steps: ['Choose a subtree in a local CJSON file.', 'Capture it as a named workspace recipe.', 'Search recipes and inspect their requirements before reuse.'],
    needs: 'A local CJSON file and an unambiguous subtree selector.',
    limit: 'Captured recipes are not automatically refreshed. Reuse must account for IDs and referenced dependencies.',
    commands: ['uc-storefront recipe capture <file> <selector> --name <name>', 'uc-storefront recipe list', 'uc-storefront recipe search <query>'],
    doc: 'widget-recipes.md', access: 'Local',
  },
  {
    id: 'preview', category: 'Preview & publish', icon: 'browser', title: 'See it before publishing',
    description: 'View supported staged content on a whole page in your own browser.',
    outcome: 'Inspect a proposed visual change in the context of the store.', tags: 'chrome preview browser locked staging review mobile',
    steps: ['Start a preview session and stage the complete set of changed containers.', 'Open a short-lived access link in your browser.', 'Verify the staged content, navigate the store, and end the session.'],
    needs: 'A user login, storefront/theme IDs, and supported container files.',
    limit: 'Preview does not stage every store setting. New theme container files must first exist on an inactive theme. Preview links are single-use and expire after two minutes.',
    commands: ['uc-storefront sf preview start --storefront <id>', 'uc-storefront sf preview stage --help', 'uc-storefront sf preview open --help'],
    doc: 'preview.md', access: 'Temporary preview',
  },
  {
    id: 'publish', category: 'Preview & publish', icon: 'history', title: 'Publish with a way back',
    description: 'Use saved baselines, conflict checks, and file history to manage changes.',
    outcome: 'A reviewed content update with a known prior file version.', tags: 'push pull publish revert rollback history versions undo conflicts',
    steps: ['Pull and save the original content and its hash baseline.', 'Preview and validate before a guarded push.', 'Inspect file versions and restore a reviewed prior version if needed.'],
    needs: 'The correct destination, a saved baseline, and the required write permissions.',
    limit: 'File version recovery is not a store-wide rollback. Shared live data can change outside theme files. General .vm, .js, and .html body writes are not supported.',
    commands: ['uc-storefront sf files versions <path> --storefront <id>', 'uc-storefront sf push --help', 'uc-storefront sf files revert --help'],
    doc: 'remote-writes.md', access: 'Live write',
  },
  {
    id: 'experiment', category: 'Improve', icon: 'split', title: 'Compare two approaches',
    description: 'Run supported page or URL experiments and inspect their results.',
    outcome: 'Evidence to evaluate a specific change to the store.', tags: 'AB A/B test experiment conversion performance variants split',
    steps: ['Choose an objective and build the control and alternative.', 'Preview each variation, then start an authorized experiment.', 'Read the results and end with or without a winner.'],
    needs: 'Publish permissions, prepared variations, and enough relevant traffic for a useful test.',
    limit: 'The CLI starts page-body and URL experiments. Theme-container experiments start in the Visual Builder. A winner flag alone is not proof of significance.',
    commands: ['uc-storefront sf experiments objectives --storefront <id>', 'uc-storefront sf experiments list --storefront <id>', 'uc-storefront sf experiments get <experiment-id> --storefront <id>'],
    doc: 'experiments.md', access: 'Live experiment',
  },
  {
    id: 'recordings', category: 'Improve', icon: 'play', title: 'Understand a shopper’s visit',
    description: 'Inspect recorded page views and replay selected moments in Chrome.',
    outcome: 'A timeline and visual evidence of what happened during a visit.', tags: 'recordings video replay shopper visitor behavior rage click analytics',
    steps: ['Check recording status and identify a relevant recorded session.', 'Read its summary and choose specific page views.', 'With permission, render a timeline, screenshots, or optional video.'],
    needs: 'Existing recordings, authorized access, and installed Chrome for replay.',
    limit: 'Enabling recording does not create past history and may incur charges. Replay can contain visitor input. Script-driven elements may look different.',
    commands: ['uc-storefront sf recordings status --storefront <id>', 'uc-storefront sf recordings show <uuid> --storefront <id>'],
    doc: 'recordings.md', access: 'Visitor data',
  },
].map(capability => ({ ...capability, source: reference + capability.doc }));
