import {useEffect,useId,useRef,useState} from 'react';
import {useRpc} from '@get-bb/plugin-sdk/app';
import type {rpcContract,Selection} from './connection-contract';
import type {HeatmapFilters,HeatmapPreview,HeatmapResult,HeatmapLocation} from './heatmap-contract';
import {Button} from './components/ui/button';
import './heatmap.css';
export function HeatmapPanel({selection,path}:{selection:Selection,path:string}) {
  const rpc=useRpc<typeof rpcContract>();const uid=useId();const generation=useRef(0);
  const today=new Date().toISOString().slice(0,10);
  const [filters,setFilters]=useState<HeatmapFilters>({from:new Date(Date.now()-6*86400000).toISOString().slice(0,10),to:today,device:'mobile'});
  const [preview,setPreview]=useState<HeatmapPreview|null>(null);const [result,setResult]=useState<HeatmapResult|null>(null);const [location,setLocation]=useState<HeatmapLocation|null>(null);
  const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [metric,setMetric]=useState<'clicks'|'movements'>('clicks');
  useEffect(()=>{generation.current++;setPreview(null);setResult(null);setLocation(null);setBusy(false);setError('');return ()=>{generation.current++;};},[selection.profileId,selection.merchantId,selection.storefront.id,selection.verifiedAt,path]);
  function update(next:HeatmapFilters){generation.current++;setFilters(next);setPreview(null);setResult(null);setLocation(null);setError('');}
  async function act(work:(active:()=>boolean)=>Promise<void>){const current=++generation.current;const active=()=>current===generation.current;setBusy(true);setError('');try{await work(active);}catch(e){if(active())setError(e instanceof Error?e.message:'The heatmap request failed.');}finally{if(active())setBusy(false);}}
  const total=result ? result[metric]:0; const max=result?Math.max(1,...result.rows.map(r=>r[metric])):1;
  return <section className="uc-heatmap" aria-labelledby={`${uid}-heading`}>
    <header><div><p className="uc-eyebrow">SHOPPER BEHAVIOR</p><h3 id={`${uid}-heading`}>Heatmaps</h3></div><span className="uc-heatmap-tag">Read only</span></header>
    <p className="uc-heatmap-scope">{selection.merchantId} · {selection.storefront.host}{path}</p>
    <p>Compare recorded clicks, pointer movements, and scroll depth. Preview the warehouse scan before you run it. Requires local BigQuery access to this merchant.</p>
    <div className="uc-heatmap-filters"><label htmlFor={`${uid}-from`}>From (UTC)<input id={`${uid}-from`} type="date" value={filters.from} disabled={busy} onChange={e=>update({...filters,from:e.target.value})}/></label><label htmlFor={`${uid}-to`}>Through (UTC)<input id={`${uid}-to`} type="date" value={filters.to} disabled={busy} onChange={e=>update({...filters,to:e.target.value})}/></label><label htmlFor={`${uid}-device`}>Device<select id={`${uid}-device`} value={filters.device} disabled={busy} onChange={e=>update({...filters,device:e.target.value as HeatmapFilters['device']})}><option value="mobile">Mobile</option><option value="desktop">Desktop</option><option value="tablet">Tablet</option></select></label></div>
    <div className="uc-heatmap-actions"><Button variant="outline" size="sm" disabled={busy} onClick={()=>act(async active=>{const next=await rpc.call('previewHeatmap',{selection,path,filters});if(active()){setPreview(next);setResult(null);setLocation(null);}})}>{busy?'Working…':'Preview heatmap scan'}</Button>{preview&&!result&&<Button size="sm" disabled={busy} onClick={()=>act(async active=>{const next=await rpc.call('runHeatmap',{selection,path,ticket:preview.ticket});if(active()){setResult(next);setLocation(null);}})}>Run reviewed scan</Button>}</div>
    {error&&<p className="uc-connect-error" role="alert">{error}</p>}
    {preview&&<div className="uc-heatmap-receipt"><p>Estimated scan: {(preview.receipt.estimatedBytes/1024**2).toFixed(2)} MiB. Ceiling: 1 GiB. Project: <code>{preview.receipt.project}</code>. {result?'Executed.':'Preview only. Running can incur BigQuery charges.'}</p><details><summary>Query and scope</summary><pre>{preview.sql}\n{preview.parameters.join('\n')}</pre><p>Preview expires {new Date(preview.expiresAt).toLocaleTimeString()}.</p></details></div>}
    {result&&<><div className="uc-heatmap-summary"><span><strong>{result.clicks.toLocaleString()}</strong> Recorded clicks</span><span><strong>{result.movements.toLocaleString()}</strong> Pointer movements</span><span><strong>{result.heatmapRows.toLocaleString()}</strong> Heatmap rows</span></div>
      {result.heatmapRows===0?<p className="uc-heatmap-empty">No heatmap rows match this host, path, date range, and device. This does not prove recording is disabled. Data exists only from when recording started; access and retention can also affect coverage.</p>:<><h4>Scroll depth</h4><div className="uc-heatmap-scroll">{(['p25','median','p75'] as const).map(key=><div key={key}><span>{key==='median'?'Median':key.toUpperCase()}</span><strong>{result.scroll[key]===null?'Unavailable':`${result.scroll[key]?.toFixed(1)}%`}</strong>{result.scroll[key]!==null&&<meter min={0} max={100} value={result.scroll[key]!} aria-label={`${key} scroll depth`}/>}</div>)}</div><p className="uc-heatmap-note">Quartiles describe scroll percentages in heatmap rows. Rows are not unique visitors or sessions.</p>
      <div className="uc-heatmap-subheading"><h4>Element intensity</h4><label htmlFor={`${uid}-metric`}>Metric <select id={`${uid}-metric`} value={metric} onChange={e=>setMetric(e.target.value as 'clicks'|'movements')}><option value="clicks">Clicks</option><option value="movements">Pointer movements</option></select></label></div>
      <p className="uc-heatmap-note">Top 40 elements ranked by clicks. Color compares the selected metric with the highest value in this list. Share uses all elements in the query. This view does not place events on page pixels.</p>
      {result.rows.length===0&&<p>No element events were returned for these heatmap rows.</p>}
      <ol className="uc-heatmap-elements">{result.rows.map((row,index)=><li key={`${row.selector}-${index}`}><div className="uc-heatmap-element" style={{backgroundColor:`rgba(245, 118, 38, ${0.05+0.3*row[metric]/max})`}}><code>{row.selector}</code><span>{row[metric].toLocaleString()} · {total?(100*row[metric]/total).toFixed(1):'0.0'}%</span><Button size="sm" variant="ghost" disabled={busy} onClick={()=>act(async active=>{const next=await rpc.call('locateHeatmap',{selection,path,selector:row.selector});if(active())setLocation(next);})}>Find widget</Button></div><div className="uc-heatmap-bar" aria-hidden="true"><span style={{width:`${100*row[metric]/max}%`}}/></div></li>)}</ol></>}
      <p className="uc-heatmap-note">Loaded {new Date(result.fetchedAt).toLocaleString()}. Click counts include repeat clicks. Pointer movement is not proof of attention. Historical selectors can differ from the current theme.</p></>}
    {location&&<div className="uc-heatmap-location" role="status"><h4>Widget lookup</h4><p>{location.reason}</p>{location.matches.map((match,index)=><div key={index}><strong>{match.title||match.type||match.id}</strong><p>{match.excerpt}</p><code>{match.file} · {match.path}</code></div>)}{location.warnings.map((warning,index)=><p key={index}>{warning}</p>)}</div>}
    <p className="uc-heatmap-note">This panel does not enable recording. A scan reads existing aggregated data. Page URLs use exact host and path matching, with index.html and query strings removed.</p>
  </section>;
}
